version: "3.9"
services:
  some-redis:
    image: redis
    ports:
      - "6379:6379"

  some-mysql:
    build: ./mysql
    ports:
      - "3306:3306"
  
  api_client:
    # image:
    #   snatiolam/redbici2
    build:
      context: ..
      dockerfile: ./raid/crud/Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    depends_on:
      - some-redis
      - some-mysql
          condition: service_healthy
    links:
      - some-mysql
    ports:
      - "3000:3000"
    restart: always