version: "3.9"
services:
  # some-redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"

  mysqldb:
    build: ./mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      # test: ["CMD-SHELL", " netstat -an | grep -q 3306"]
      # timeout: 20s
      # retries: 10
      # interval: 10s

  authms:
    # image:
    #   snatiolam/redbici2
    build:
      context: ../auth-ms
      args:
        DOCKER_BUILDKIT: 1
    env_file:
      - ../auth-ms/.env
    depends_on:
      mysqldb:
        condition: service_healthy

    ports:
      - "5000:5000"
    restart: always
      

  api_client:
    # image:
    #   snatiolam/redbici2
    build:
      context: ../crud
      args:
        DOCKER_BUILDKIT: 1
    depends_on:
      mysqldb:
        condition: service_healthy
      

    ports:
      - "3000:3000"
    restart: always